MovieReview/Controllers/MovieReviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MovieReview.Models;
using System.Data.Entity;

namespace MovieReview.Controllers
{

    public class MovieReviewsController : Controller
    {

        MovieDb _db = new MovieDb();
        //
        // GET: /MovieReviews/
        public ActionResult Index([Bind(Prefix = "id")] int movieId)
        {
            var movie = _db.Movies.Find(movieId);
            if (movie != null)
            {
                return View(movie);
            }
            return HttpNotFound();
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model = _db.MovieReviews.Find(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit([Bind(Exclude = "ReviewerName")]MovieReviews review)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(review).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index", new { id = review.MovieId });
            }
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }
    }
}       
   

MovieReview/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                @*     <li>@Html.ActionLink("Reviews", "Index", "MovieReviews")*@
                    <li>@Html.ActionLink("Movies", "Index", "Movies")</li>
                @*  <li>@Html.Partial("_LoginPartial")</li>*@
            

                </ul>
                <p class="nav navbar-text navbar-right">Hola, @User.Identity.Name!</p>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

   @* @Scripts.Render("~/bundles/jquery")*@
    @Scripts.Render("~/bundles/movies")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>